{"name": "test_create_duplicate_courier_fail", "status": "passed", "description": "Проверка создания двух одинаковых курьеров: статус 409; в ответе \"Этот логин уже используется\"", "start": 1722979544630, "stop": 1722979544796, "uuid": "1ab9d4d7-cb4d-4d36-8d34-6d417e5aba63", "historyId": "23c66a1a87a569e76bf5bf5bfd67ee1a", "testCaseId": "23c66a1a87a569e76bf5bf5bfd67ee1a", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_duplicate_courier_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "14364-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}