{"name": "test_incorrect_login_or_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 404 and '{\"code\":404,... не найдена\"}' == 'Учетная запись не найдена'\n +  where 404 = <Response [404]>.status_code\n  \n  - Учетная запись не найдена\n  + {\"code\":404,\"message\":\"Учетная запись не найдена\"})", "trace": "self = <tests.test_login_courier.TestLoginCourier object at 0x000001C095968F10>\n\n    @allure.description('Проверка:неправильные логин или пароль возвращают ошибку \"Учетная запись не найдена\", статус 404')\n    def test_incorrect_login_or_password(self):\n        response = requests.post(f'{url.SQOOTER_URL}/api/v1/courier/login',\n                                 json={\"login\": \"wrong_login\", \"password\": \"wrong_password\"})\n>       assert response.status_code == 404 and response.text == \"Учетная запись не найдена\"\nE       assert (404 == 404 and '{\"code\":404,... не найдена\"}' == 'Учетная запись не найдена'\nE        +  where 404 = <Response [404]>.status_code\nE         \nE         - Учетная запись не найдена\nE         + {\"code\":404,\"message\":\"Учетная запись не найдена\"})\n\ntests\\test_login_courier.py:24: AssertionError"}, "description": "Проверка:неправильные логин или пароль возвращают ошибку \"Учетная запись не найдена\", статус 404", "start": 1722544239787, "stop": 1722544240029, "uuid": "0a02c8d9-b08b-4068-ab5a-ac6cfa06075f", "historyId": "73c6ca00e006afc070591083f504f957", "testCaseId": "73c6ca00e006afc070591083f504f957", "fullName": "tests.test_login_courier.TestLoginCourier#test_incorrect_login_or_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "17016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}